services:
  table-tv:
    build:
      context: .
      dockerfile: Dockerfile
      target: table-tv
    ports:
      - "80:80"
    hostname: table-tv
    volumes:
      - table-tv-data:/app/data

volumes:
  table-tv-data:
