services:
  table-tv:
    build:
      context: .
      dockerfile: Dockerfile
      target: table-tv
    environment:
      - USE_STUNNEL_FOR_RTMPS=${USE_STUNNEL_FOR_RTMPS:-}
    ports:
      - "80:80"
    hostname: table-tv
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - table-tv-data:/app/data
      - ./.env:/app/.env

volumes:
  table-tv-data:
